export const questions = [
  {
    no: 1,
    instruction:"Passage You want to hit a small box on the floor with a marble fired from a spring-loaded gun that is mounted on a table. The target box is a distance R horizontally from the edge of the table; see the figure to the right. You compress the spring a distance d, but the center of the marble falls short by a distance r of the center of the box. How far should you compress the spring to score a direct hit (neglect friction)?",
    question: "How many tentacles do octopuses have?",
    options: [2, 4, 5, 8],
    correctOpton: 4,
  },
  {
    no: 2,
    instruction:"Passage You want to hit a small box on the floor with a marble fired from a spring-loaded gun that is mounted on a table. The target box is a distance R horizontally from the edge of the table; see the figure to the right. You compress the spring a distance d, but the center of the marble falls short by a distance r of the center of the box. How far should you compress the spring to score a direct hit (neglect friction)?",
    question: "What is the shape of the moon?",
    options: ["round", "square", "half circle", "semi circle"],
    correctOpton: 2,
  },
  {
    no: 3,
    instruction:"Passage You want to hit a small box on the floor with a marble fired from a spring-loaded gun that is mounted on a table. The target box is a distance R horizontally from the edge of the table; see the figure to the right. You compress the spring a distance d, but the center of the marble falls short by a distance r of the center of the box. How far should you compress the spring to score a direct hit (neglect friction)?",
    question: "How many ears do human beings have?",
    correctOpton: 4,
    options: [2, 4, 5, 8],
    correctOpton: 1,
  },
  {
    no: 4,
    instruction:"Passage You want to hit a small box on the floor with a marble fired from a spring-loaded gun that is mounted on a table. The target box is a distance R horizontally from the edge of the table; see the figure to the right. You compress the spring a distance d, but the center of the marble falls short by a distance r of the center of the box. How far should you compress the spring to score a direct hit (neglect friction)?",
    question: "How many lives do cats have?",
    options: [2, 4, 10, 9],
    correctOpton: 4,
  },
  {
    no: 5,
    instruction:"Passage You want to hit a small box on the floor with a marble fired from a spring-loaded gun that is mounted on a table. The target box is a distance R horizontally from the edge of the table; see the figure to the right. You compress the spring a distance d, but the center of the marble falls short by a distance r of the center of the box. How far should you compress the spring to score a direct hit (neglect friction)?",
    question: "How many pets should you keep?",
    options: [2, 4, 5, "None"],
    correctOpton: 4,
  },
  {
    no: 6,
    instruction:"Passage You want to hit a small box on the floor with a marble fired from a spring-loaded gun that is mounted on a table. The target box is a distance R horizontally from the edge of the table; see the figure to the right. You compress the spring a distance d, but the center of the marble falls short by a distance r of the center of the box. How far should you compress the spring to score a direct hit (neglect friction)?",
    question: "What would be your weapon of choice in a vampire attack?",
    options: ["cross", "holy water", "run", "flirt"],
    correctOpton: 2,
  },
  {
    no: 7,
    instruction:"Passage You want to hit a small box on the floor with a marble fired from a spring-loaded gun that is mounted on a table. The target box is a distance R horizontally from the edge of the table; see the figure to the right. You compress the spring a distance d, but the center of the marble falls short by a distance r of the center of the box. How far should you compress the spring to score a direct hit (neglect friction)?",
    question: "Is the sky blue? If no, which color?",
    options: ["Yes", "Transparent", "Purple", "Black"],
    correctOpton: 2,
  },
  {
    no: 8,
    instruction:"Passage You want to hit a small box on the floor with a marble fired from a spring-loaded gun that is mounted on a table. The target box is a distance R horizontally from the edge of the table; see the figure to the right. You compress the spring a distance d, but the center of the marble falls short by a distance r of the center of the box. How far should you compress the spring to score a direct hit (neglect friction)?",
    question: "How many hours should you sleep?",
    options: [2, 4, "Pretend to sleep", "No sleep"],
    correctOpton: 3,
  },
  {
    no: 9,
    instruction:"Passage You want to hit a small box on the floor with a marble fired from a spring-loaded gun that is mounted on a table. The target box is a distance R horizontally from the edge of the table; see the figure to the right. You compress the spring a distance d, but the center of the marble falls short by a distance r of the center of the box. How far should you compress the spring to score a direct hit (neglect friction)?",
    question: "How many stars can we see in the night sky?",
    options: [200, 400, "Multibillion", "Who cares"],
    correctOpton: 3,
  },
  {
    no: 10,
    instruction:"Passage You want to hit a small box on the floor with a marble fired from a spring-loaded gun that is mounted on a table. The target box is a distance R horizontally from the edge of the table; see the figure to the right. You compress the spring a distance d, but the center of the marble falls short by a distance r of the center of the box. How far should you compress the spring to score a direct hit (neglect friction)?",
    question: "What is the name of the nearest star?",
    options: ["Moon", "Serius", "Wolf 359", "Sun"],
    correctOpton: 1,
  },
];
